feat : Create method to verify words
TechQuack/pattedoie pull request #53
Opened 2024-11-28 21:46 UTC by Erwann27

2024-11-28 21:50 UTC, EllexArt requested changes

2024-11-28 21:50 UTC, EllexArt commented on PatteDoie/Services/Scattergories/ScattegoriesService.cs
> +                    Text = "",
pas mieux de mettre null que chaine vide ?

2024-11-28 21:50 UTC, Zounkla commented on PatteDoie/Services/Scattergories/ScattegoriesService.cs
> +        private static bool IsAllWordChecked(ScattergoriesGame game)
Peut-être plus appeler : AreAllWordsChecked ?

2024-11-28 21:51 UTC, Zounkla commented on PatteDoie/Services/Scattergories/ScattegoriesService.cs
> +                var awnsers = player.Answers;
awnsers -> answers

2024-11-28 21:53 UTC, Erwann27 commented on PatteDoie/Services/Scattergories/ScattegoriesService.cs
> +                    Text = "",
le champ Text est en required, donc je pense que c'est pas mal

2024-11-28 21:53 UTC, Erwann27 commented on PatteDoie/Services/Scattergories/ScattegoriesService.cs
> +        private static bool IsAllWordChecked(ScattergoriesGame game)
j'ai hésité, donc je sais pas les 2 me choquent pas

2024-11-28 21:55 UTC, Zounkla commented on PatteDoie/Views/ScattergoriesGames/ComputeScore.razor.cs
> +                Console.WriteLine("c'est good");
à retirer

2024-11-29 08:44 UTC, Erwann27 commented on PatteDoie/Views/ScattergoriesGames/ComputeScore.razor.cs
> +                Console.WriteLine("c'est good");
Visiblement le commentaire est marqué comme outdated, donc le fichier a peut être bel et bien sauté

2024-11-29 14:24 UTC, Lucy-Nightgold approved these changes

2024-11-29 14:36 UTC, merged